
export const continents = [
  { id: "AF", name: "África" },
  { id: "AS", name: "Ásia" },
  { id: "EU", name: "Europa" },
  { id: "NA", name: "América do Norte" },
  { id: "SA", name: "América do Sul" },
  { id: "OC", name: "Oceania" },
];

export const countriesByContinent: { [key: string]: { id: string; name: string }[] } = {
  AF: [
    { id: "DZ", name: "Argélia" },
    { id: "AO", name: "Angola" },
    { id: "CM", name: "Camarões" },
    { id: "CI", name: "Costa do Marfim" },
    { id: "EG", name: "Egito" },
    { id: "GA", name: "Gana" },
    { id: "MA", name: "Marrocos" },
    { id: "NG", name: "Nigéria" },
    { id: "SN", name: "Senegal" },
    { id: "ZA", name: "África do Sul" },
    { id: "TN", name: "Tunísia" },
  ],
  AS: [
    { id: "AU", name: "Austrália" },
    { id: "CN", name: "China" },
    { id: "IR", name: "Irã" },
    { id: "IQ", name: "Iraque" },
    { id: "JP", name: "Japão" },
    { id: "QA", name: "Catar" },
    { id: "SAU", name: "Arábia Saudita" },
    { id: "KR", name: "Coreia do Sul" },
    { id: "AE", name: "Emirados Árabes Unidos" },
    { id: "UZ", name: "Uzbequistão" },
  ],
  EU: [
    { id: "AL", name: "Albânia" },
    { id: "AT", name: "Áustria" },
    { id: "BY", name: "Bielorrússia" },
    { id: "BE", name: "Bélgica" },
    { id: "BA", name: "Bósnia e Herzegovina" },
    { id: "BG", name: "Bulgária" },
    { id: "HR", name: "Croácia" },
    { id: "CY", name: "Chipre" },
    { id: "CZ", name: "Tchéquia" },
    { id: "DK", name: "Dinamarca" },
    { id: "ENG", name: "Inglaterra" },
    { id: "ES", name: "Espanha" },
    { id: "EE", name: "Estônia" },
    { id: "FI", name: "Finlândia" },
    { id: "FR", name: "França" },
    { id: "DE", name: "Alemanha" },
    { id: "GR", name: "Grécia" },
    { id: "HU", name: "Hungria" },
    { id: "IS", name: "Islândia" },
    { id: "IE", name: "Irlanda" },
    { id: "IL", name: "Israel" },
    { id: "IT", name: "Itália" },
    { id: "LV", name: "Letônia" },
    { id: "LT", name: "Lituânia" },
    { id: "LU", name: "Luxemburgo" },
    { id: "MT", name: "Malta" },
    { id: "MD", name: "Moldávia" },
    { id: "ME", name: "Montenegro" },
    { id: "NL", name: "Holanda" },
    { id: "MK", name: "Macedônia do Norte" },
    { id: "NIR", name: "Irlanda do Norte" },
    { id: "NO", name: "Noruega" },
    { id: "PL", name: "Polônia" },
    { id: "PT", name: "Portugal" },
    { id: "RO", name: "Romênia" },
    { id: "RU", name: "Rússia" },
    { id: "SCO", name: "Escócia" },
    { id: "RS", name: "Sérvia" },
    { id: "SK", name: "Eslováquia" },
    { id: "SI", name: "Eslovênia" },
    { id: "SE", name: "Suécia" },
    { id: "CH", name: "Suíça" },
    { id: "TR", name: "Turquia" },
    { id: "UA", name: "Ucrânia" },
    { id: "WAL", name: "País de Gales" },
  ],
  NA: [
    { id: "CA", name: "Canadá" },
    { id: "CR", name: "Costa Rica" },
    { id: "SV", name: "El Salvador" },
    { id: "GT", name: "Guatemala" },
    { id: "HT", name: "Haiti" },
    { id: "HN", name: "Honduras" },
    { id: "JM", name: "Jamaica" },
    { id: "MX", name: "México" },
    { id: "PA", name: "Panamá" },
    { id: "TT", name: "Trinidad e Tobago" },
    { id: "US", name: "Estados Unidos" },
  ],
  SA: [
    { id: "AR", name: "Argentina" },
    { id: "BO", name: "Bolívia" },
    { id: "BR", name: "Brasil" },
    { id: "CL", name: "Chile" },
    { id: "CO", name: "Colômbia" },
    { id: "EC", name: "Equador" },
    { id: "PY", name: "Paraguai" },
    { id: "PE", name: "Peru" },
    { id: "UY", name: "Uruguai" },
    { id: "VE", name: "Venezuela" },
  ],
  OC: [
    { id: "NZ", name: "Nova Zelândia" },
    { id: "FJ", name: "Fiji" },
    { id: "NC", name: "Nova Caledônia" },
    { id: "PG", name: "Papua-Nova Guiné" },
    { id: "SB", name: "Ilhas Salomão" },
    { id: "TAH", name: "Taiti" },
  ],
};
